{{- if and .Values.global.secret.enabled (gt (len .Values.global.secret.stringData) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hiclaw.shared.envFromSecretName" . }}
  namespace: {{ include "hiclaw.namespace" . }}
  labels:
    {{- include "hiclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.global.secret.stringData }}
  {{ $k }}: {{ $v | toString | quote }}
{{- end }}
{{- end }}
