{{- if (include "hiclaw.isGenericK8s" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hiclaw.minio.fullname" . }}
  namespace: {{ include "hiclaw.namespace" . }}
  labels:
    {{- include "hiclaw.minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.rootPassword | quote }}
{{- end }}
