package credentials

import (
	"context"
	"fmt"

	"github.com/hiclaw/hiclaw-controller/internal/credprovider"
)

// STSConfig holds configuration for the STS token service.
type STSConfig struct {
	// OSSBucket is the bucket name that scoped tokens are restricted to.
	// It is also returned to callers as part of STSToken.OSSBucket so
	// they know which bucket the issued token is valid against.
	OSSBucket string
}

// STSService issues scoped STS tokens by delegating to the
// hiclaw-credential-provider sidecar via a credprovider.Client.
//
// The service is agnostic to how the sidecar actually produces the
// tokens: the production sidecar calls AssumeRoleWithOIDC, the
// mock-credential-provider calls AssumeRole with a long-lived AK/SK, but
// both speak the same HTTP contract.
type STSService struct {
	config   STSConfig
	provider credprovider.Client
}

// NewSTSService constructs an STSService that delegates token issuance to
// the given credprovider.Client. A nil provider disables the service and
// causes IssueToken to fail — it is up to the caller (server wiring) to
// translate that into a 503 at the HTTP edge.
func NewSTSService(cfg STSConfig, provider credprovider.Client) *STSService {
	return &STSService{config: cfg, provider: provider}
}

// Configured reports whether a credential provider has been wired in.
// Callers can use this to gate the exposure of credential-related HTTP
// endpoints in deployments that do not run the sidecar.
func (s *STSService) Configured() bool {
	return s != nil && s.provider != nil
}

// IssueWorkerToken asks the sidecar for an STS triple scoped to the
// given worker name and the configured OSS bucket. The inline policy is
// generated by the sidecar based on role=worker.
func (s *STSService) IssueWorkerToken(ctx context.Context, workerName string) (*STSToken, error) {
	if !s.Configured() {
		return nil, fmt.Errorf("STS service not configured: no credential provider URL set")
	}
	resp, err := s.provider.Issue(ctx, credprovider.IssueRequest{
		Role:   credprovider.RoleWorker,
		Name:   workerName,
		Bucket: s.config.OSSBucket,
	})
	if err != nil {
		return nil, err
	}
	return &STSToken{
		AccessKeyID:     resp.AccessKeyID,
		AccessKeySecret: resp.AccessKeySecret,
		SecurityToken:   resp.SecurityToken,
		Expiration:      resp.Expiration,
		ExpiresInSec:    resp.ExpiresInSec,
		OSSEndpoint:     resp.Endpoint,
		OSSBucket:       s.config.OSSBucket,
	}, nil
}
